# Library loading

In [1]:
import os
import csv
import numpy as np
import random
import pandas as pd
import time
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import f1_score,accuracy_score
import matplotlib.pyplot as plt

# Load Data

In [2]:
csv_lines = [] #preallocate list for extracted csv lines

path_to_csv = "data/dataset.csv"

raw_data = pd.read_csv(path_to_csv, sep=';')

# encode as nominal
#raw_data.user.unique(); raw_data.user = raw_data.user.map({'debora':0, 'katia':1, 'wallace':2, 'jose_carlos':3}); raw_data.user.unique()
raw_data.gender.unique(); raw_data.gender = raw_data.gender.map({'Woman':1, 'Man':0}); raw_data.gender.unique()

#raw_data.class.unique(); raw_data.class = raw_data.class.map({'sitting':0, 'sittingdown':1, 'standing':2, 'standingup':3, 'walking:4'}); raw_data.class.unique()


raw_data.head()

B:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (5,17) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,user,gender,age,how_tall_in_meters,weight,body_mass_index,x1,y1,z1,x2,y2,z2,x3,y3,z3,x4,y4,z4,class
0,debora,1,46,"1,62",75,"28,6",-3,92,-63,-23,18,-19,5,104,-92,-150,-103,-147,sitting
1,debora,1,46,"1,62",75,"28,6",-3,94,-64,-21,18,-18,-14,104,-90,-149,-104,-145,sitting
2,debora,1,46,"1,62",75,"28,6",-1,97,-61,-12,20,-15,-13,104,-90,-151,-104,-144,sitting
3,debora,1,46,"1,62",75,"28,6",-2,96,-57,-15,21,-16,-13,104,-89,-153,-103,-142,sitting
4,debora,1,46,"1,62",75,"28,6",-1,96,-61,-13,20,-15,-13,104,-89,-153,-104,-143,sitting

# Replace , with . in data

In [3]:
raw_data['how_tall_in_meters'] = raw_data['how_tall_in_meters'].str.replace(',', '.')
raw_data['body_mass_index'] = raw_data['body_mass_index'].str.replace(',', '.')

raw_data.head()

,user,gender,age,how_tall_in_meters,weight,body_mass_index,x1,y1,z1,x2,y2,z2,x3,y3,z3,x4,y4,z4,class
0,debora,1,46,1.62,75,28.6,-3,92,-63,-23,18,-19,5,104,-92,-150,-103,-147,sitting
1,debora,1,46,1.62,75,28.6,-3,94,-64,-21,18,-18,-14,104,-90,-149,-104,-145,sitting
2,debora,1,46,1.62,75,28.6,-1,97,-61,-12,20,-15,-13,104,-90,-151,-104,-144,sitting
3,debora,1,46,1.62,75,28.6,-2,96,-57,-15,21,-16,-13,104,-89,-153,-103,-142,sitting
4,debora,1,46,1.62,75,28.6,-1,96,-61,-13,20,-15,-13,104,-89,-153,-104,-143,sitting

# check if data have NULL value or not.

In [4]:
raw_data[pd.isnull(raw_data).any(axis=1)]

raw_data.isnull().values.any(); raw_data.isnull().sum().sum()

raw_data.shape

(165633, 19)

In [5]:
raw_data.drop(raw_data[raw_data.z4 == "-14420-11-2011 04:50:23,713"].index.values, inplace=True) # row 122076 -> (165633, 19)
raw_data.z4 = pd.to_numeric(raw_data.z4, errors='raise'); raw_data.dtypes # z4 object -> int64
raw_data.columns

raw_data[pd.isnull(raw_data).any(axis=1)] # show missing column

,user,gender,age,how_tall_in_meters,weight,body_mass_index,x1,y1,z1,x2,y2,z2,x3,y3,z3,x4,y4,z4,class
163840,jose_carlos,0,75,1.67,67,NaN,2,96,-126,41,51,-65,3,123,-113,-200,-87,-161,walking
163841,jose_carlos,0,75,1.67,67,NaN,-23,83,-137,-28,105,-131,0,160,-117,-195,-58,-149,walking
163842,jose_carlos,0,75,1.67,67,NaN,-10,87,-145,-25,86,-100,77,12,-84,-186,-87,-139,walking
163843,jose_carlos,0,75,1.67,67,NaN,-17,88,-144,-18,86,-96,0,95,-114,-189,-85,-142,walking
163844,jose_carlos,0,75,1.67,67,NaN,-11,103,-136,-14,92,-93,38,121,-97,-189,-92,-144,walking
163845,jose_carlos,0,75,1.67,67,NaN,14,68,-147,-54,94,-112,86,173,-73,-193,-63,-152,walking
163846,jose_carlos,0,75,1.67,67,NaN,-3,75,-149,-61,104,-118,20,121,-126,-197,-97,-126,walking
163847,jose_carlos,0,75,1.67,67,NaN,-6,77,-147,-3,84,-99,19,125,-122,-210,-76,-154,walking
163848,jose_carlos,0,75,1.67,67,NaN,-4,94,-137,7,61,-97,14,121,-119,-201,-88,-157,walking
163849,jose_carlos,0,75,1.67,67,NaN,6,92,-140,9,76,-27,10,124,-119,-203,-83,-158,walking
163850,jose_carlos,0,75,1.67,67,NaN,-23,96,-140,12,66,-129,-7,140,-123,-202,-79,-154,walking
163851,jose_carlos,0,75,1.67,67,NaN,-13,85,-145,-31,79,-114,59,42,-97,-194,-72,-139,walking
163852,jose_carlos,0,75,1.67,67,NaN,-13,86,-150,-25,80,-106,12,87,-141,-194,-95,-154,walking
163853,jose_carlos,0,75,1.67,67,NaN,-15,99,-138,-24,87,-101,25,125,-115,-193,-90,-150,walking
163854,jose_carlos,0,75,1.67,67,NaN,14,72,-148,-18,82,-102,136,175,-70,-196,-61,-150,walking
163855,jose_carlos,0,75,1.67,67,NaN,-3,67,-158,-57,95,-127,18,118,-123,-192,-94,-131,walking
163856,jose_carlos,0,75,1.67,67,NaN,-13,73,-149,4,93,-95,26,124,-116,-200,-82,-159,walking
163857,jose_carlos,0,75,1.67,67,NaN,-2,93,-140,0,65,-92,16,120,-128,-204,-92,-149,walking
163858,jose_carlos,0,75,1.67,67,NaN,-2,86,-136,7,82,-27,13,122,-121,-200,-82,-157,walking
163859,jose_carlos,0,75,1.67,67,NaN,8,114,-145,-15,60,-117,-6,143,-119,-212,-80,-150,walking
163860,jose_carlos,0,75,1.67,67,NaN,-23,85,-163,-20,87,-104,-5,145,-121,-187,-96,-144,walking
163861,jose_carlos,0,75,1.67,67,NaN,-16,91,-138,-26,86,-94,32,81,-129,-185,-90,-145,walking
163862,jose_carlos,0,75,1.67,67,NaN,-16,94,-134,-17,89,-99,33,183,-78,-190,-88,-143,walking
163863,jose_carlos,0,75,1.67,67,NaN,-2,87,-173,-35,111,-94,37,118,-140,-221,-77,-137,walking
163864,jose_carlos,0,75,1.67,67,NaN,8,101,-169,-19,124,-109,17,123,-104,-186,-78,-149,walking
163865,jose_carlos,0,75,1.67,67,NaN,-10,85,-148,1,88,-105,14,126,-114,-213,-74,-149,walking
163866,jose_carlos,0,75,1.67,67,NaN,-15,104,-134,-96,54,-70,13,123,-118,-224,-89,-152,walking
163867,jose_carlos,0,75,1.67,67,NaN,-12,85,-144,-68,96,-165,10,139,-99,-233,-97,-154,walking
163868,jose_carlos,0,75,1.67,67,NaN,-20,85,-140,-29,80,-86,46,72,-118,-176,-91,-144,walking
163869,jose_carlos,0,75,1.67,67,NaN,-15,101,-142,-17,90,-106,-24,210,-91,-181,-97,-145,walking
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165603,jose_carlos,0,75,1.67,67,NaN,-39,147,-198,4,133,-40,-79,136,-28,-188,-95,-157,walking
165604,jose_carlos,0,75,1.67,67,NaN,7,109,-154,15,98,-69,-99,229,42,-181,-85,-147,walking
165605,jose_carlos,0,75,1.67,67,NaN,-18,110,-138,-4,97,-99,-109,170,-96,-186,-95,-154,walking
165606,jose_carlos,0,75,1.67,67,NaN,3,112,-139,8,95,-74,-123,226,-117,-191,-74,-152,walking
165607,jose_carlos,0,75,1.67,67,NaN,-3,69,-180,-33,105,-105,-43,168,-127,-197,-39,-144,walking
165608,jose_carlos,0,75,1.67,67,NaN,-35,71,-187,-47,91,-93,2,189,-127,-169,-27,-146,walking
165609,jose_carlos,0,75,1.67,67,NaN,-26,120,-153,-31,106,-95,199,174,-152,-192,-77,-147,walking
165610,jose_carlos,0,75,1.67,67,NaN,13,66,-181,-46,93,-86,-47,159,-128,-206,-44,-142,walking
165611,jose_carlos,0,75,1.67,67,NaN,-22,106,-189,-27,131,-76,-142,180,-57,-205,-113,-147,walking
165612,jose_carlos,0,75,1.67,67,NaN,8,114,-174,-36,86,-112,13,170,-130,-172,-106,-123,walking
165613,jose_carlos,0,75,1.67,67,NaN,-7,99,-139,-22,78,-104,11,179,-78,-197,-96,-135,walking
165614,jose_carlos,0,75,1.67,67,NaN,-14,117,-155,-23,98,-85,-126,161,-70,-184,-108,-154,walking
165615,jose_carlos,0,75,1.67,67,NaN,-6,103,-157,-6,95,-117,5,120,-127,-194,-77,-159,walking
165616,jose_carlos,0,75,1.67,67,NaN,-17,84,-157,-10,83,-122,4,116,-117,-198,-76,-156,walking
165617,jose_carlos,0,75,1.67,67,NaN,-11,87,-153,-7,87,-115,8,117,-114,-202,-81,-162,walking
165618,jose_carlos,0,75,1.67,67,NaN,-4,88,-158,1,88,-98,10,119,-119,-190,-73,-160,walking
165619,jose_carlos,0,75,1.67,67,NaN,-8,85,-154,-3,94,-106,13,123,-117,-194,-79,-163,walking
165620,jose_carlos,0,75,1.67,67,NaN,1,92,-154,-2,84,-104,12,121,-128,-198,-79,-165,walking
165621,jose_carlos,0,75,1.67,67,NaN,-1,91,-154,-5,72,-83,9,118,-122,-200,-80,-164,walking
165622,jose_carlos,0,75,1.67,67,NaN,-2,94,-147,6,73,-89,9,118,-120,-201,-78,-165,walking
165623,jose_carlos,0,75,1.67,67,NaN,-3,96,-147,6,81,-90,15,120,-118,-200,-80,-166,walking
165624,jose_carlos,0,75,1.67,67,NaN,-10,94,-149,-10,87,-95,12,121,-117,-189,-81,-159,walking
165625,jose_carlos,0,75,1.67,67,NaN,-8,94,-150,-8,89,-104,14,119,-101,-193,-77,-153,walking
165626,jose_carlos,0,75,1.67,67,NaN,-6,96,-142,-2,91,-103,14,121,-102,-194,-78,-156,walking
165627,jose_carlos,0,75,1.67,67,NaN,-13,94,-150,-13,88,-98,16,120,-99,-194,-79,-157,walking
165628,jose_carlos,0,75,1.67,67,NaN,2,93,-148,-8,88,-100,15,120,-100,-189,-77,-160,walking
165629,jose_carlos,0,75,1.67,67,NaN,-1,94,-147,-17,87,-99,17,121,-99,-190,-78,-158,walking
165630,jose_carlos,0,75,1.67,67,NaN,-10,93,-143,-19,86,-104,0,114,-101,-185,-80,-153,walking
165631,jose_carlos,0,75,1.67,67,NaN,-15,86,-152,-19,88,-117,-44,155,-25,-185,-84,-156,walking
165632,jose_carlos,0,75,1.67,67,NaN,-14,86,-144,-18,85,-107,-3,114,-128,-210,-88,-148,walking

In [6]:
# Missing data count

raw_data = raw_data[raw_data['body_mass_index'].notnull()]

raw_data[pd.isnull(raw_data).any(axis=1)]

raw_data.isnull().values.any(); raw_data.isnull().sum().sum()

0

# Create y that contain label of data

In [7]:
y = raw_data['class'].copy()
type(y); y.describe(); y.head(3); y.shape; y.unique() # (165632, )

# y = pd.get_dummies(y, columns=['class'])

y = y.map({'sitting':0, 'sittingdown':1, 'standing':2, 'standingup':3, 'walking':4})

# Drop user and class

In [8]:
raw_data.drop(labels=['user', 'class'], axis=1, inplace=True); raw_data.shape # (165632, 17)
raw_data.head()

,gender,age,how_tall_in_meters,weight,body_mass_index,x1,y1,z1,x2,y2,z2,x3,y3,z3,x4,y4,z4
0,1,46,1.62,75,28.6,-3,92,-63,-23,18,-19,5,104,-92,-150,-103,-147
1,1,46,1.62,75,28.6,-3,94,-64,-21,18,-18,-14,104,-90,-149,-104,-145
2,1,46,1.62,75,28.6,-1,97,-61,-12,20,-15,-13,104,-90,-151,-104,-144
3,1,46,1.62,75,28.6,-2,96,-57,-15,21,-16,-13,104,-89,-153,-103,-142
4,1,46,1.62,75,28.6,-1,96,-61,-13,20,-15,-13,104,-89,-153,-104,-143

# Split data to train/ test by Hold-out

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(raw_data, y, test_size=0.30, random_state=7)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((114687, 17), (49152, 17), (114687,), (49152,))

In [10]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import  classification_report
from sklearn.metrics import mean_squared_error

# thang đo MSE, F-measure, precision, recall, accuracy

s= time.time()
clf = DecisionTreeClassifier().fit(X_train, y_train)
y_pred = clf.predict(X_test)
print("Fitting completed in: ", time.time() - s)

mse = mean_squared_error(y_test, y_pred)

print('MSE = ', mse)
print(classification_report(y_test, y_pred))

Fitting completed in:  1.5313642024993896
MSE =  0.059346516927083336
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     15224
           1       0.95      0.95      0.95      3498
           2       0.99      0.99      0.99     14073
           3       0.94      0.94      0.94      3782
           4       0.99      0.98      0.98     12575

    accuracy                           0.98     49152
   macro avg       0.97      0.97      0.97     49152
weighted avg       0.98      0.98      0.98     49152

In [11]:
import pickle

# save the model to disk

filename = 'DCSTree.sav'
pickle.dump(clf, open(filename, 'wb'))
 
# some time later...
 
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))